services:
  runner:
    build: ./langgraph
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CREDENTIALS_JSON: ${GOOGLE_CREDENTIALS_JSON}
      GMAIL_TOKEN_JSON: ${GMAIL_TOKEN_JSON}
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      GOOGLE_SHEETS_CREDENTIALS: ${GOOGLE_SHEETS_CREDENTIALS}
      GOOGLE_SHEET_NAME: ${GOOGLE_SHEET_NAME}
      GMAIL_TOKEN_PKL_BASE64: ${GMAIL_TOKEN_PKL_BASE64}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${GOOGLE_SERVICE_ACCOUNT_JSON}
      SENDER_EMAIL:  ${SENDER_EMAIL}
      SENDER_EMAIL_PASSWORD: ${SENDER_EMAIL_PASSWORD}
      RECEIVER_EMAIL: ${RECEIVER_EMAIL}
    volumes:
    - ./credentials:/app/credentials:rw

    depends_on:
      redis:
        condition: service_healthy
    command: python /app/run_daily.py