services:
  runner:
    build: ./langgraph
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CREDENTIALS_JSON: ${GOOGLE_CREDENTIALS_JSON}
      GMAIL_TOKEN_JSON: ${GMAIL_TOKEN_JSON}
      CREDENTIALS_DIR: /app/credentials
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      GOOGLE_SHEETS_CREDENTIALS: ${GOOGLE_SHEETS_CREDENTIALS}
      GOOGLE_SHEET_NAME: ${GOOGLE_SHEET_NAME}

    depends_on:
      redis:
        condition: service_healthy
    command: python /app/run_daily.py