name: daily-job-tracker
on:
  schedule:
    - cron: "0 13 * * *"   # 9:00 AM New York (EDT)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
      GMAIL_TOKEN_PKL_BASE64: ${{ secrets.GMAIL_TOKEN_PKL_BASE64 }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
      LANGSMITH_TRACING: ${{ secrets.LANGSMITH_TRACING }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker compose -f docker-compose.yml -f compose.ci.yml build

      # A) Usually you only need runner + redis
      - name: Check OPENAI_API_KEY present
        run: |
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "OPENAI_API_KEY missing - continuing without OpenAI-dependent steps"
          else
            echo "OPENAI_API_KEY is set"
          fi
      - name: Run daily job (runner + redis)
        run: |
          docker compose -f docker-compose.yml -f compose.ci.yml up \
            --abort-on-container-exit --exit-code-from runner \
            runner redis-sub redis

      # B) If your daily job needs the subscriber alive too, use this instead:
      - name: Run daily job with subscriber
        run: |
          docker compose -f docker-compose.yml -f compose.ci.yml up \
            --abort-on-container-exit --exit-code-from runner \
            runner redis-sub redis

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml -f compose.ci.yml down -v