name: daily-job-tracker
on:
  schedule:
    - cron: "0 13 * * *"   # 9:00 AM New York (EDT)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker compose -f docker-compose.yml -f compose.ci.yml build

      # A) Usually you only need runner + redis
      - name: Run daily job (runner + redis)
        run: |
          docker compose -f docker-compose.yml -f compose.ci.yml up \
            --abort-on-container-exit --exit-code-from runner \
            runner redis

      # B) If your daily job needs the subscriber alive too, use this instead:
      # - name: Run daily job with subscriber
      #   run: |
      #     docker compose -f docker-compose.yml -f compose.ci.yml up \
      #       --abort-on-container-exit --exit-code-from runner \
      #       runner redis-sub redis

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml -f compose.ci.yml down -v